export const ADD_BOOK_ERROR = "ADD_BOOK_ERROR";
export const ADD_BOOK_LOADING = "ADD_BOOK_LOADING";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";

export const DELETE_BOOK_ERROR = "DELETE_BOOK_ERROR";
export const DELETE_BOOK_LOADING = "DELETE_BOOK_LOADING";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";

export const EDIT_BOOK_ERROR = "EDIT_BOOK_ERROR";
export const EDIT_BOOK_LOADING = "EDIT_BOOK_LOADING";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";

export const FETCH_BOOKS_ERROR = "FETCH_BOOK_ERROR";
export const FETCH_BOOKS_LOADING = "FETCH_BOOK_LOADING";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOK_SUCCESS";



export const ADD_PRODUCT_ERROR = " ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
export const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";
export const EDIT_PRODUCT_LOADING = "EDIT_PRODUCT_LOADING";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const FETCH_PRODUCT_LOADING = "FETCH_PRODUCT_LOADING";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

